name: Test Runner Configuration and Deploy Code

on:
  push:
    branches:
      - main

jobs:
  test-runner:
    runs-on: windows-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Check if runner is configured
        run: |
          echo "Checking if runner is configured..."
          echo "Runner OS: ${runner.os}"
          echo "Runner architecture: ${runner.arch}"
          echo "Runner environment variables:"
          env

      - name: Copy code to another Windows machine using PowerShell
        run: |
          $target = "\\${{ secrets.WINDOWS_HOST }}\testing" # This must be the shared folder on the target machine
          $username = "${{ secrets.WINDOWS_RDP_USER }}"
          $password = "${{ secrets.WINDOWS_RDP_PASSWORD }}"
          $secpasswd = ConvertTo-SecureString $password -AsPlainText -Force
          $credentials = New-Object System.Management.Automation.PSCredential ($username, $secpasswd)
          
          # Map network drive
          New-PSDrive -Name Z -PSProvider FileSystem -Root $target -Credential $credentials -Persist
          
          # Copy files to target machine
          Copy-Item -Path "." -Destination "Z:\testing" -Recurse -Force
          
          # Remove network drive
          Remove-PSDrive -Name Z
        shell: pwsh
