on:
  push:
    branches:
      - main  # Adjust this to your default branch or other branches you want to deploy

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Upload files to Windows Server
      run: |
        echo "${{ secrets.WINDOWS_RDP_PASSWORD }}" | powershell -Command "scp -o StrictHostKeyChecking=no -r ./ ${{ secrets.WINDOWS_RDP_USER }}@${{ secrets.WINDOWS_HOST }}:C:\Users\migspfs001\Desktop"

    - name: Restart IIS Application Pool
      uses: azure/powershell@v1
      with:
        inlineScript: |
          $username = "${{ secrets.WINDOWS_RDP_USER }}"
          $password = ConvertTo-SecureString "${{ secrets.WINDOWS_RDP_PASSWORD }}" -AsPlainText -Force
          $cred = New-Object System.Management.Automation.PSCredential($username, $password)
          $session = New-PSSession -ComputerName ${{ secrets.WINDOWS_HOST }} -Credential $cred
          Invoke-Command -Session $session -ScriptBlock {
              Restart-WebAppPool -Name "YourAppPoolName"
          }
          Remove-PSSession -Session $session
