name: Test Runner Configuration

on:
  push:
    branches:
      - main

jobs:
  test-runner:
    runs-on: windows-latest
    steps:
      - name: Check if runner is configured
        run: |
          echo "Checking if runner is configured..."
          echo "Runner OS: ${runner.os}"
          echo "Runner architecture: ${runner.arch}"
          echo "Runner environment variables:"
          env
